target:
	javac Clock.java -d ./ -classpath ./
	javac Currency.java -d ./ -classpath ./
	javac LocalClock.java -d ./ -classpath ./
	javac Msg.java -d ./ -classpath ./
	javac Dispatcher.java -d ./ -classpath ./
	javac Worker.java -d ./ -classpath ./
	javac Lamport.java -d ./ -classpath ./
